/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ahmedmq.boot.chatgpt.dalle.storyteller.images;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StoryEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4811650707516350174L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StoryEvent\",\"namespace\":\"com.ahmedmq.boot.chatgpt.dalle.storyteller.images\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"int\",\"connect.default\":0},\"default\":0},{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"scene\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"created_at\",\"type\":{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.MicroTimestamp\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StoryEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StoryEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StoryEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StoryEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StoryEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StoryEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StoryEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StoryEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StoryEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private java.lang.CharSequence title;
  private java.lang.CharSequence scene;
  private long created_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StoryEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param title The new value for title
   * @param scene The new value for scene
   * @param created_at The new value for created_at
   */
  public StoryEvent(java.lang.Integer id, java.lang.CharSequence title, java.lang.CharSequence scene, java.lang.Long created_at) {
    this.id = id;
    this.title = title;
    this.scene = scene;
    this.created_at = created_at;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return title;
    case 2: return scene;
    case 3: return created_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: scene = (java.lang.CharSequence)value$; break;
    case 3: created_at = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'scene' field.
   * @return The value of the 'scene' field.
   */
  public java.lang.CharSequence getScene() {
    return scene;
  }


  /**
   * Sets the value of the 'scene' field.
   * @param value the value to set.
   */
  public void setScene(java.lang.CharSequence value) {
    this.scene = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public long getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.created_at = value;
  }

  /**
   * Creates a new StoryEvent RecordBuilder.
   * @return A new StoryEvent RecordBuilder
   */
  public static com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder newBuilder() {
    return new com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder();
  }

  /**
   * Creates a new StoryEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StoryEvent RecordBuilder
   */
  public static com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder newBuilder(com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder other) {
    if (other == null) {
      return new com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder();
    } else {
      return new com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder(other);
    }
  }

  /**
   * Creates a new StoryEvent RecordBuilder by copying an existing StoryEvent instance.
   * @param other The existing instance to copy.
   * @return A new StoryEvent RecordBuilder
   */
  public static com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder newBuilder(com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent other) {
    if (other == null) {
      return new com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder();
    } else {
      return new com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for StoryEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StoryEvent>
    implements org.apache.avro.data.RecordBuilder<StoryEvent> {

    private int id;
    private java.lang.CharSequence title;
    private java.lang.CharSequence scene;
    private long created_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.scene)) {
        this.scene = data().deepCopy(fields()[2].schema(), other.scene);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.created_at)) {
        this.created_at = data().deepCopy(fields()[3].schema(), other.created_at);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing StoryEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.scene)) {
        this.scene = data().deepCopy(fields()[2].schema(), other.scene);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.created_at)) {
        this.created_at = data().deepCopy(fields()[3].schema(), other.created_at);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'scene' field.
      * @return The value.
      */
    public java.lang.CharSequence getScene() {
      return scene;
    }


    /**
      * Sets the value of the 'scene' field.
      * @param value The value of 'scene'.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder setScene(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.scene = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'scene' field has been set.
      * @return True if the 'scene' field has been set, false otherwise.
      */
    public boolean hasScene() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'scene' field.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder clearScene() {
      scene = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder setCreatedAt(long value) {
      validate(fields()[3], value);
      this.created_at = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public com.ahmedmq.boot.chatgpt.dalle.storyteller.images.StoryEvent.Builder clearCreatedAt() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StoryEvent build() {
      try {
        StoryEvent record = new StoryEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.scene = fieldSetFlags()[2] ? this.scene : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.created_at = fieldSetFlags()[3] ? this.created_at : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StoryEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<StoryEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StoryEvent>
    READER$ = (org.apache.avro.io.DatumReader<StoryEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    if (this.title == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.title);
    }

    if (this.scene == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.scene);
    }

    out.writeLong(this.created_at);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.title = null;
      } else {
        this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.scene = null;
      } else {
        this.scene = in.readString(this.scene instanceof Utf8 ? (Utf8)this.scene : null);
      }

      this.created_at = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.title = null;
          } else {
            this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.scene = null;
          } else {
            this.scene = in.readString(this.scene instanceof Utf8 ? (Utf8)this.scene : null);
          }
          break;

        case 3:
          this.created_at = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










